[package]
name = "oxidize-injection"
version.workspace = true
edition.workspace = true

[dependencies]
oxidize-domain = { workspace = true }
oxidize-usecase = { workspace = true }
oxidize-infrastructure = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
